[completion]
copilot = false
activate_on_typing = true

[display]
default_table_page_size = 10
default_width = "full"
theme = "light"
dataframes = "rich"
cell_output = "below"
code_editor_font_size = 15

[ai]
rules = ""
[ai.bedrock]


[ai.open_ai]
model = "claude-3-7-sonnet-20250219"

[ai.google]

[package_management]
manager = "uv"

[snippets]
custom_paths = []
include_default_snippets = true

[language_servers.pylsp]
enable_mypy = true
enable_pydocstyle = false
enable_flake8 = false
enable_pylint = false
enabled = true
enable_ruff = true
enable_pyflakes = false

[runtime]
pythonpath = []
auto_instantiate = true
std_stream_max_bytes = 1000000
on_cell_change = "autorun"
watcher_on_save = "lazy"
auto_reload = "lazy"
reactive_tests = true
default_sql_output = "auto"
output_max_bytes = 8000000

[server]
browser = "default"
follow_symlink = false

[experimental]

[keymap]
preset = "vim"

[keymap.overrides]
"cell.focusUp" = "Alt-Shift-k"
"cell.focusDown" = "Alt-Shift-j"
"global.focusTop" = "Alt-Shift-f"
"global.focusBottom" = "Alt-Shift-g"
"cell.createAbove" = "Alt-Shift-o"
"cell.createBelow" = "Alt-Shift-p"
"cell.moveUp" = "Ctrl-Alt-k"
"cell.moveDown" = "Ctrl-Alt-j"

[formatting]
line_length = 88

[save]
format_on_save = false
autosave_delay = 1000
autosave = "after_delay"
